version: '2'

services:

  cups:
    build: cups
    ports:
     - "631:631"
    networks:
     - print
    environment:
     NODE_ENV: local
    volumes:
     - printers:/usr/share/cups/drivers
     - /dev/bus/usb:/dev/bus/usb

  samba:
    build: samba
    ports:
     - "139:139"
     - "445:445"
    volumes:
     - printers:/home/drivers
    networks:
     - print
    environment:
     NODE_ENV: local

  avahi:
    build: avahi
    ports:
     - "5353:5353"
    networks:
     - print

networks:
  print:
    driver: bridge

volumes:
  printers: